### ISSUE TITLE
BB10 device Null Pointer Exception

### ISSUE THREAD

**Issue by td0** [ant-ife/awesome-fastclick#6]
Somehow we found BB10 device which has no `Version` keyword within the User-Agent.

It causes NPE error when 
`blackberryVersion = navigator.userAgent.match(/Version\/([0-9]*)\.([0-9]*)/);` 
is undefined, then in the next line within the if condition, `blackberryVersion` referenced using array index of `[1]` and `[2]`

![image](https://user-images.githubusercontent.com/4467386/81810167-b4b47580-954c-11ea-92e6-e26b632dd8c1.png)

**Comment by brucejcw** [comment]
#7
